version: '3'

services: 
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
  mongo:
    image: "mongo"
    ports:
      - 27017:27017
  
  nginx:
    image: nginx:alpine
    ports: 
      - 80:80
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
